# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gop < Formula
  desc "simple cli app to open current git repository's remote url in the default browser."
  homepage "https://github.com/akadir/gop"
  version "0.0.3-beta"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akadir/gop/releases/download/v0.0.3-beta/gop_0.0.3-beta_macOS-64bit.tar.gz"
      sha256 "1ded15c2085bd1bc7ea911382ead45b30662a13fb102706fe10132ef3a19dcfe"
    end
    if Hardware::CPU.arm?
      url "https://github.com/akadir/gop/releases/download/v0.0.3-beta/gop_0.0.3-beta_macOS-ARM64.tar.gz"
      sha256 "83aa676452f48808d5cadbc5f4710f142c2ec8eb3db98147362aa8c7872e3d7c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/akadir/gop/releases/download/v0.0.3-beta/gop_0.0.3-beta_Linux-64bit.tar.gz"
      sha256 "08d7bdfb73d7313a9a4c3040ae214f3f08e1de999fc32117408bccceb01539d5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akadir/gop/releases/download/v0.0.3-beta/gop_0.0.3-beta_Linux-ARM64.tar.gz"
      sha256 "447cc1b95118110f8216ef7f3edf0e76417b5e4fdd81a95b51ac235c70313c8e"
    end
  end

  def install
    bin.install "gop"
  end
end
