# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gop < Formula
  desc "simple cli app to open current git repository's remote url in the default browser."
  homepage "https://github.com/akadir/gop"
  version "0.7.4"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/akadir/gop/releases/download/v0.7.4/gop_0.7.4_macOS_ARM64.tar.gz"
      sha256 "816bd975258a87b29298b0451f39949d3eeeb9595bcc90aa178a50ac8b93b448"

      def install
        bin.install "gop"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akadir/gop/releases/download/v0.7.4/gop_0.7.4_macOS_64bit.tar.gz"
      sha256 "820c13e316e191ef58e0db4173157e7fc5d1552e28e895f4dbac0401a17a6d82"

      def install
        bin.install "gop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akadir/gop/releases/download/v0.7.4/gop_0.7.4_Linux_ARM64.tar.gz"
      sha256 "29ceaae3cae93dae10e0201974ab6708e3fd9c1ceab44b3cec38d1774a58cd7a"

      def install
        bin.install "gop"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akadir/gop/releases/download/v0.7.4/gop_0.7.4_Linux_64bit.tar.gz"
      sha256 "0734216203054d999602daa2c08fa37c7943479d50dcece76dfa0f3a7c15de9d"

      def install
        bin.install "gop"
      end
    end
  end
end
