# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gop < Formula
  desc "simple cli app to open current git repository's remote url in the default browser."
  homepage "https://github.com/akadir/gop"
  version "0.6.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/akadir/gop/releases/download/v0.6.2/gop_0.6.2_macOS_ARM64.tar.gz"
      sha256 "9e89906fbd32f885956205fbbbac5d82663dc7436871517e83f79ec228ac844c"

      def install
        bin.install "gop"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akadir/gop/releases/download/v0.6.2/gop_0.6.2_macOS_64bit.tar.gz"
      sha256 "798a4bc010cfc7fa50296379e6d4a8877eb52c4ad4490ddd656f42daa366eeb5"

      def install
        bin.install "gop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akadir/gop/releases/download/v0.6.2/gop_0.6.2_Linux_ARM64.tar.gz"
      sha256 "1717867acef17cf2a618a9a079ebdb03457dd622f04489724189ac09d7d1cccb"

      def install
        bin.install "gop"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akadir/gop/releases/download/v0.6.2/gop_0.6.2_Linux_64bit.tar.gz"
      sha256 "43eb1c22fb165cdfd21bb9f25ce67871f0a109b5840d6345369b75ba4b856e4e"

      def install
        bin.install "gop"
      end
    end
  end

  depends_on "git"
end
